/**
 * Headless usage examples for solar-power-budget.
 *
 * Demonstrates:
 * 1. Single evaluation of orbit-averaged solar array power
 * 2. Mission lifetime degradation sweep
 * 3. Contract connection check with orbital-thermal-limits
 */

import { solarPowerBudget } from './module';
import { canConnect } from '../../../core/contract';

// 1. Single evaluation
const result = solarPowerBudget.run({
  solarArrayAreaM2: 8.0,
  baseCellEfficiency: 0.31,
  cellOperatingTempC: 60,
  missionDurationYears: 5,
  orbitAltitudeKm: 600,
  orbitInclinationDeg: 97.8,
  orbitRaanDeg: 68.7,
});

console.log('--- Solar Power Budget (Single Evaluation) ---');
console.log(`Orbit-averaged Power: ${result.values.orbitAveragePowerW.toFixed(1)} W`);
console.log(`Instantaneous Power (EOL): ${result.values.instantaneousSunlitPowerW.toFixed(1)} W`);
console.log(`BOL Peak Power (STC): ${result.values.beginningOfLifePowerW.toFixed(1)} W`);
console.log(`Sunlit Fraction: ${(result.values.orbitSunlitFraction * 100).toFixed(1)}%`);
console.log(`Orbit Period: ${result.values.orbitPeriodMinutes.toFixed(1)} min`);
console.log(`Energy per Orbit: ${result.values.orbitEnergyGeneratedWh.toFixed(1)} W·h`);
console.log(`Effective System Efficiency: ${(result.values.effectiveSystemEfficiency * 100).toFixed(2)}%`);

// 2. Mission degradation sweep: how much does power drop from Year 0 to Year 15?
console.log('\n--- Mission Degradation Sweep ---');
for (const yr of [0, 1, 3, 5, 7, 10, 15]) {
  const sweep = solarPowerBudget.run({ solarArrayAreaM2: 8.0, missionDurationYears: yr });
  console.log(`Year ${yr.toString().padStart(2)}: ${sweep.values.orbitAveragePowerW.toFixed(1)} W (rad derate: ${(sweep.values.radiationDerateFactor * 100).toFixed(1)}%)`);
}

// 3. Dimensional connection check to orbital-thermal-limits
const solarOut = solarPowerBudget.descriptor.outputs.find((o) => o.key === 'orbitAveragePowerW')!;
const targetInput = {
  key: 'externalGeneratedPowerW',
  label: 'External solar generation',
  unit: 'W',
  dimension: { mass: 1, length: 2, time: -3 },
  description: 'Average electrical power generated by an external solar array module.',
  defaultValue: 0,
};

console.log('\n--- Ecosystem Connection Check ---');
console.log('canConnect(orbitAveragePowerW -> externalGeneratedPowerW):', canConnect(solarOut, targetInput));
