import {
  DIMENSIONLESS,
  DIM_ANGLE,
  DIM_AREA,
  DIM_ENERGY,
  DIM_IRRADIANCE,
  DIM_LENGTH,
  DIM_PER_TEMPERATURE,
  DIM_POWER,
  DIM_TEMPERATURE,
  DIM_TIME,
  resolveInputs,
  type Diagnostic,
  type ModuleDescriptor,
  type ModuleResult,
  type OutputSpec,
  type PortSpec,
  type SandboxModule,
} from '../../../core/contract';
import { DAWN_DUSK_SSO_ORBIT } from '../../../core/orbitalMechanics';
import { MODULE_CONTRACT_VERSION, MODULE_RELEASE_VERSION } from '../version';
import { runSolarKernel, solarKernelWarnings, type SolarKernelInputs, type SolarKernelOutputs } from './kernel';

export const INPUT_SPECS: PortSpec[] = [
  {
    key: 'solarArrayAreaM2',
    label: 'Solar array area',
    unit: 'm²',
    dimension: DIM_AREA,
    min: 0.1,
    max: 5e7,
    defaultValue: 4.0,
    description: 'Total active photovoltaic cell aperture area across deployed wings or body-mounted panels.',
    typicalSource: 'A spacecraft mass and volume budget module.',
  },
  {
    key: 'baseCellEfficiency',
    label: 'Cell efficiency (STC)',
    unit: '',
    dimension: DIMENSIONLESS,
    min: 0.05,
    max: 0.50,
    defaultValue: 0.30,
    description: 'Bolometric cell efficiency at Standard Test Conditions (STC: 28 °C, AM0 1361 W/m²). Representative of modern triple-junction GaAs space cells (~30-32%) or high-efficiency silicon (~20-22%).',
  },
  {
    key: 'solarFluxWm2',
    label: 'Solar irradiance',
    unit: 'W/m²',
    dimension: DIM_IRRADIANCE,
    min: 1200,
    max: 1500,
    defaultValue: 1361,
    description: 'Solar flux incident at 1 AU (Earth orbit distance). Adjusted seasonally for perihelion/aphelion.',
  },
  {
    key: 'cellOperatingTempC',
    label: 'Cell operating temperature',
    unit: '°C',
    dimension: DIM_TEMPERATURE,
    min: -100,
    max: 180,
    defaultValue: 65,
    description: 'Equilibrium temperature of the solar array in direct sunlight.',
  },
  {
    key: 'tempCoefficientPwr',
    label: 'Temperature coefficient',
    unit: '1/K',
    dimension: DIM_PER_TEMPERATURE,
    min: -0.006,
    max: 0,
    defaultValue: -0.0025,
    description: 'Fractional change in power output per Kelvin increase above STC 28 °C (typically -0.20% to -0.30%/K for multi-junction GaAs).',
  },
  {
    key: 'missionDurationYears',
    label: 'Mission duration',
    unit: 'yr',
    dimension: DIM_TIME,
    min: 0,
    max: 30,
    defaultValue: 5.0,
    description: 'Elapsed mission lifetime over which space radiation fluence degrades cell junctions.',
  },
  {
    key: 'annualDegradationRate',
    label: 'Annual degradation rate',
    unit: '',
    dimension: DIMENSIONLESS,
    min: 0,
    max: 0.10,
    defaultValue: 0.015,
    description: 'Compound annual performance degradation rate due to trapped proton/electron radiation and coverglass darkening (typically ~1-2%/yr in LEO).',
  },
  {
    key: 'pointingEfficiency',
    label: 'Pointing factor',
    unit: '',
    dimension: DIMENSIONLESS,
    min: 0,
    max: 1.0,
    defaultValue: 0.98,
    description: 'Cosine alignment factor cos(theta) accounting for solar array drive tracking error or sun angle off-normal.',
  },
  {
    key: 'bosEfficiency',
    label: 'Balance of system efficiency',
    unit: '',
    dimension: DIMENSIONLESS,
    min: 0.5,
    max: 1.0,
    defaultValue: 0.88,
    description: 'Combined efficiency of cell packing density, coverglass transmission, blocking diode drops, harness I²R losses, and MPPT/PCDU conversion.',
  },
  {
    key: 'orbitAltitudeKm',
    label: 'Perigee altitude',
    unit: 'km',
    dimension: DIM_LENGTH,
    min: 160,
    max: 40000,
    defaultValue: DAWN_DUSK_SSO_ORBIT.orbitAltitudeKm,
    description: 'Altitude above mean Earth radius at closest approach. Determines orbital period and shadow geometry.',
  },
  {
    key: 'orbitEccentricity',
    label: 'Orbital eccentricity',
    unit: '',
    dimension: DIMENSIONLESS,
    min: 0,
    max: 0.95,
    defaultValue: DAWN_DUSK_SSO_ORBIT.orbitEccentricity,
    description: 'Shape of the orbit; 0 is circular.',
  },
  {
    key: 'orbitInclinationDeg',
    label: 'Orbital inclination',
    unit: '°',
    dimension: DIM_ANGLE,
    min: 0,
    max: 180,
    defaultValue: DAWN_DUSK_SSO_ORBIT.orbitInclinationDeg,
    description: 'Tilt of the orbital plane relative to Earth equator.',
  },
  {
    key: 'orbitRaanDeg',
    label: 'Right ascension of ascending node',
    unit: '°',
    dimension: DIM_ANGLE,
    min: 0,
    max: 360,
    defaultValue: DAWN_DUSK_SSO_ORBIT.orbitRaanDeg,
    description: 'Orientation of the orbital plane about Earth polar axis relative to the Sun vector.',
  },
  {
    key: 'orbitArgumentDeg',
    label: 'Argument of perigee',
    unit: '°',
    dimension: DIM_ANGLE,
    min: 0,
    max: 360,
    defaultValue: DAWN_DUSK_SSO_ORBIT.orbitArgumentDeg,
    description: 'Orientation of the ellipse within its orbital plane.',
  },
];

export const OUTPUT_SPECS: OutputSpec[] = [
  {
    key: 'orbitAveragePowerW',
    label: 'Orbit average electrical power',
    unit: 'W',
    dimension: DIM_POWER,
    kind: 'quantity',
    description: 'Time-averaged electrical power delivered to the spacecraft bus over a full orbit, including eclipse and all losses. Feeds orbital-thermal-limits.',
  },
  {
    key: 'instantaneousSunlitPowerW',
    label: 'Instantaneous sunlit power (EOL)',
    unit: 'W',
    dimension: DIM_POWER,
    kind: 'quantity',
    description: 'Electrical power generated while illuminated in direct sunlight at operating temperature and end-of-life condition.',
  },
  {
    key: 'beginningOfLifePowerW',
    label: 'Beginning-of-life power (BOL)',
    unit: 'W',
    dimension: DIM_POWER,
    kind: 'quantity',
    description: 'Peak electrical power at launch under Standard Test Conditions (28 °C, no radiation degradation).',
  },
  {
    key: 'orbitSunlitFraction',
    label: 'Orbit sunlit fraction',
    unit: '',
    dimension: DIMENSIONLESS,
    kind: 'indicator',
    description: 'Fraction of the orbital period spent illuminated by the Sun (1.0 indicates no eclipse).',
  },
  {
    key: 'orbitEclipseDurationMin',
    label: 'Eclipse duration per orbit',
    unit: 'min',
    dimension: DIM_TIME,
    kind: 'indicator',
    description: 'Duration spent in Earth cylindrical shadow per orbital revolution, in minutes.',
  },
  {
    key: 'orbitPeriodMinutes',
    label: 'Orbital period',
    unit: 'min',
    dimension: DIM_TIME,
    kind: 'indicator',
    description: 'Keplerian orbital revolution period in minutes.',
  },
  {
    key: 'orbitEnergyGeneratedWh',
    label: 'Orbit electrical energy',
    unit: 'W·h',
    dimension: DIM_ENERGY,
    kind: 'quantity',
    description: 'Gross electrical energy delivered to the bus over one full revolution.',
  },
  {
    key: 'effectiveSystemEfficiency',
    label: 'Effective system efficiency',
    unit: '',
    dimension: DIMENSIONLESS,
    kind: 'indicator',
    description: 'Net efficiency from incident solar flux to delivered electrical power in sunlight.',
  },
  {
    key: 'temperatureDerateFactor',
    label: 'Temperature derating factor',
    unit: '',
    dimension: DIMENSIONLESS,
    kind: 'indicator',
    description: 'Efficiency multiplier due to cell operating temperature relative to STC 28 °C.',
  },
  {
    key: 'radiationDerateFactor',
    label: 'Radiation degradation factor',
    unit: '',
    dimension: DIMENSIONLESS,
    kind: 'indicator',
    description: 'Efficiency multiplier due to cumulative radiation damage over the mission duration.',
  },
];

export const DESCRIPTOR: ModuleDescriptor = {
  id: 'solar-power-budget',
  releaseVersion: MODULE_RELEASE_VERSION,
  contractVersion: MODULE_CONTRACT_VERSION,
  title: 'Solar array electrical power budget',
  summary: 'Orbit-averaged electrical power generation for orbital solar arrays, incorporating eclipse geometry, pointing accuracy, multi-junction cell temperature derating, radiation fluence degradation, and balance-of-system losses.',
  domains: ['photovoltaics', 'orbital mechanics', 'power systems', 'space environment'],
  inputs: INPUT_SPECS,
  outputs: OUTPUT_SPECS,
  assumptions: [
    'Eclipse duty cycle is computed using a cylindrical Earth shadow model (Earth radius 6371 km), neglecting solar penumbra and atmospheric refraction.',
    'The Sun vector is fixed in inertial space at the standard reference direction, consistent with orbital-thermal-limits.',
    'Array cell operating temperature is assumed steady during illuminated periods; rapid thermal transients during shadow egress/ingress are not modelled dynamically.',
    'Photovoltaic conversion of Earth albedo and Earth thermal IR onto solar panels is neglected (direct solar flux is treated as the sole electrical generation source).',
    'Radiation fluence and cell degradation are represented via an aggregate compound annual degradation rate rather than tracking individual junction fluences or string failures.',
    'Reported orbit-averaged electrical power is generation delivered to the bus; battery charge/discharge round-trip efficiency and energy storage losses are deferred to a battery sizing module.',
  ],
};

export type SolarPowerResult = ModuleResult<SolarKernelOutputs>;

export const solarPowerBudget: SandboxModule<SolarKernelOutputs> = {
  descriptor: DESCRIPTOR,
  run(inputs: Partial<Record<string, number>>): SolarPowerResult {
    const { resolved, diagnostics } = resolveInputs(INPUT_SPECS, inputs);
    const kernelInputs = resolved as unknown as SolarKernelInputs;
    const outputs = runSolarKernel(kernelInputs);

    const allDiagnostics: Diagnostic[] = [
      ...diagnostics,
      ...solarKernelWarnings(kernelInputs, outputs).map((message): Diagnostic => ({ severity: 'warning', message })),
    ];

    return {
      values: outputs,
      diagnostics: allDiagnostics,
      resolvedInputs: resolved,
    };
  },
};
