import type { Manifest } from '../../core/types';
import { equations } from './equations';
import { MODULE_RELEASE_VERSION, MODULE_CONTRACT_VERSION } from './version';
import { DAWN_DUSK_SSO_ORBIT } from '../../core/orbitalMechanics';

export const manifest: Manifest = {
  id: 'solar-power-budget',
  releaseVersion: MODULE_RELEASE_VERSION,
  contractVersion: MODULE_CONTRACT_VERSION,
  title: 'Solar Array Electrical Power Budget',
  summary: 'Orbit-averaged electrical power generation for orbital photovoltaic arrays, incorporating eclipse geometry, pointing accuracy, multi-junction cell temperature derating, radiation fluence degradation, and balance-of-system losses.',
  tags: ['space', 'photovoltaics', 'orbital-power', 'ai-infrastructure', 'solar-energy'],
  relatedArticles: [],
  interfaces: ['orbital-thermal-limits'],
  parameters: [
    {
      id: 'solarArrayAreaM2',
      name: 'Solar Array Area',
      unit: 'm²',
      min: 0.1,
      max: 100,
      step: 0.5,
      defaultValue: 4.0,
      description: 'Total active photovoltaic cell aperture area across deployed array wings.',
    },
    {
      id: 'baseCellEfficiency',
      name: 'Cell Efficiency (STC)',
      unit: 'η',
      min: 0.05,
      max: 0.50,
      step: 0.01,
      defaultValue: 0.30,
      description: 'Bolometric cell efficiency at Standard Test Conditions (28 °C, AM0 1361 W/m²). Modern multi-junction space cells ~30-32%.',
    },
    {
      id: 'cellOperatingTempC',
      name: 'Cell Operating Temp',
      unit: '°C',
      min: -40,
      max: 150,
      step: 1,
      defaultValue: 65,
      description: 'Equilibrium temperature of the solar array under direct solar illumination.',
    },
    {
      id: 'tempCoefficientPwr',
      name: 'Temp Coefficient',
      unit: '1/K',
      min: -0.005,
      max: 0,
      step: 0.0001,
      defaultValue: -0.0025,
      description: 'Fractional change in power output per Kelvin increase above STC 28 °C (typically -0.25%/K).',
    },
    {
      id: 'missionDurationYears',
      name: 'Mission Lifetime',
      unit: 'yr',
      min: 0,
      max: 20,
      step: 0.5,
      defaultValue: 5.0,
      description: 'Elapsed mission lifetime over which space radiation fluence degrades solar cells.',
    },
    {
      id: 'annualDegradationRate',
      name: 'Annual Degradation',
      unit: '1/yr',
      min: 0,
      max: 0.05,
      step: 0.001,
      defaultValue: 0.015,
      description: 'Compound annual performance degradation rate due to radiation fluence and coverglass darkening.',
    },
    {
      id: 'pointingEfficiency',
      name: 'Pointing Efficiency',
      unit: '0-1',
      min: 0.5,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.98,
      description: 'Cosine tracking factor accounting for solar array gimbal drive error or off-pointing.',
    },
    {
      id: 'bosEfficiency',
      name: 'Balance of System',
      unit: '0-1',
      min: 0.5,
      max: 1.0,
      step: 0.01,
      defaultValue: 0.88,
      description: 'Combined efficiency of cell packing, coverglass transmissivity, diode drops, harness I²R losses, and PCDU.',
    },
    {
      id: 'solarFluxWm2',
      name: 'Solar Irradiance',
      unit: 'W/m²',
      min: 1250,
      max: 1450,
      step: 5,
      defaultValue: 1361,
      description: 'Solar constant at Earth orbit distance (1 AU).',
    },
    {
      id: 'orbitAltitudeKm',
      name: 'Perigee Altitude',
      unit: 'km',
      min: 160,
      max: 40000,
      step: 10,
      defaultValue: DAWN_DUSK_SSO_ORBIT.orbitAltitudeKm,
      description: 'Altitude above mean Earth radius at closest approach. Directly dictates orbital period and eclipse geometry.',
    },
    {
      id: 'orbitEccentricity',
      name: 'Eccentricity',
      unit: 'e',
      min: 0,
      max: 0.90,
      step: 0.01,
      defaultValue: DAWN_DUSK_SSO_ORBIT.orbitEccentricity,
      description: 'Orbital eccentricity (0 is circular).',
    },
    {
      id: 'orbitInclinationDeg',
      name: 'Inclination',
      unit: '°',
      min: 0,
      max: 180,
      step: 1,
      defaultValue: DAWN_DUSK_SSO_ORBIT.orbitInclinationDeg,
      description: 'Tilt of the orbital plane relative to Earth equator.',
    },
    {
      id: 'orbitRaanDeg',
      name: 'RAAN',
      unit: '°',
      min: 0,
      max: 360,
      step: 1,
      defaultValue: DAWN_DUSK_SSO_ORBIT.orbitRaanDeg,
      description: 'Right ascension of ascending node, orienting the orbital plane relative to the Sun vector.',
    },
  ],
  equations,
};
