import type { Manifest } from '../../core/types';
import { equations } from './equations';

export const manifest: Manifest = {
  id: 'orbital-thermal-limits',
  title: 'Orbital Compute Thermal Rejection Limits',
  summary: 'Interactive first-order thermal balance for a spacecraft radiator in Earth orbit, including solar, albedo, Earth IR, coolant transport, and orbital geometry.',
  tags: ['space', 'thermal-physics', 'orbital-compute', 'ai-infrastructure'],
  articleUrl: 'https://thesiliconcarbide.substack.com',
  relatedArticles: [],
  parameters: [
    { id: 'radiatorArea', name: 'Radiator Surface Area', unit: 'm²', min: 0.5, max: 20, step: 0.5, defaultValue: 2, description: 'Total two-sided radiator area used by the thermal model.' },
    { id: 'emissivity', name: 'IR Emissivity', unit: 'ε', min: 0.5, max: 0.99, step: 0.01, defaultValue: 0.9, description: 'Long-wave infrared emissivity.' },
    { id: 'solarAbsorptivity', name: 'Solar Absorptivity', unit: 'α', min: 0.02, max: 0.8, step: 0.01, defaultValue: 0.12, description: 'Fraction of incident solar energy absorbed by the radiator coating.' },
    { id: 'operatingTempC', name: 'Radiator Temperature', unit: '°C', min: 20, max: 180, step: 1, defaultValue: 70, description: 'Radiator/coolant hot-side temperature.' },
    { id: 'flowRateKgS', name: 'Coolant Flow', unit: 'kg/s', min: 0.01, max: 1.5, step: 0.01, defaultValue: 0.35, description: 'Coolant mass flow rate.' },
    { id: 'sunIncidence', name: 'Sun Incidence', unit: '0–1', min: 0, max: 1, step: 0.01, defaultValue: 0.75, description: 'Cosine-like incidence factor between radiator normal and the Sun.' },
    { id: 'sinkTempK', name: 'Space Sink', unit: 'K', min: 3, max: 250, step: 1, defaultValue: 180, description: 'Effective deep-space background temperature.' },
    { id: 'earthIrTempK', name: 'Earth IR', unit: 'K', min: 180, max: 320, step: 1, defaultValue: 255, description: 'Effective Earth infrared radiating temperature.' },
    { id: 'earthAlbedo', name: 'Earth Albedo', unit: '0–1', min: 0, max: 0.9, step: 0.01, defaultValue: 0.3, description: 'Fraction of incident solar radiation reflected by Earth.' },
    { id: 'earthViewFactor', name: 'Earth View Factor', unit: '0–1', min: 0, max: 1, step: 0.01, defaultValue: 0.35, description: 'Fraction of radiator field of view occupied by Earth.' },
    { id: 'coolantDeltaT', name: 'Coolant ΔT', unit: 'K', min: 1, max: 80, step: 1, defaultValue: 10, description: 'Allowed coolant temperature rise across the payload.' },
    { id: 'parasiticHeatW', name: 'Parasitic Heat', unit: 'W', min: 0, max: 500, step: 5, defaultValue: 40, description: 'Pumps, avionics, harness and other non-compute heat entering the loop; also used as a proxy for non-compute bus electrical draw in the power budget.' },
    { id: 'computeWattsRequested', name: 'Requested Compute Power', unit: 'W', min: 0, max: 5000, step: 10, defaultValue: 300, description: 'Continuous AI compute electrical power the operator wants to run; treated as fully converting to waste heat. E.g. a single H100-class GPU is ~700 W, a GB300-class GPU is ~1400 W.' },
    { id: 'solarPanelAreaM2', name: 'Solar Array Area', unit: 'm²', min: 0.5, max: 30, step: 0.5, defaultValue: 4, description: 'Total active solar cell area across both deployed array wings.' },
    { id: 'solarPanelEfficiency', name: 'Solar Cell Efficiency', unit: 'η', min: 0.05, max: 0.4, step: 0.01, defaultValue: 0.29, description: 'Net array electrical efficiency (cell + packing + wiring losses). ~0.29 is representative of modern triple-junction space cells.' },
    { id: 'solarPanelPointingFactor', name: 'Solar Pointing Accuracy', unit: '0–1', min: 0, max: 1, step: 0.01, defaultValue: 0.95, description: 'How well the single-axis-tracking array is aimed at the Sun; 1 is perfect tracking.' },
    { id: 'orbitEccentricity', name: 'Eccentricity', unit: 'e', min: 0, max: 0.75, step: 0.01, defaultValue: 0.01, description: 'Orbital eccentricity; 0 is circular, up to ~0.74 for a Molniya-type highly elliptical orbit.' },
    { id: 'orbitAltitudeKm', name: 'Perigee Altitude', unit: 'km', min: 160, max: 40000, step: 10, defaultValue: 550, description: 'Altitude above mean Earth radius at closest approach (perigee).' },
    { id: 'orbitInclinationDeg', name: 'Inclination', unit: '°', min: 0, max: 98, step: 1, defaultValue: 51.6, description: 'Orbital inclination.' },
    { id: 'orbitRaanDeg', name: 'RAAN', unit: '°', min: 0, max: 360, step: 1, defaultValue: 25, description: 'Right ascension of the ascending node, shown as an orientation control.' },
    { id: 'orbitArgumentDeg', name: 'Argument of Perigee', unit: '°', min: 0, max: 360, step: 1, defaultValue: 0, description: 'Rotates the ellipse within its orbital plane (where perigee points); only visible when eccentricity is greater than 0.' },
    { id: 'orbitPhaseDeg', name: 'Orbital Phase', unit: '°', min: 0, max: 360, step: 1, defaultValue: 35, description: 'Satellite true anomaly \u2014 its position around the orbit, measured from perigee. Can be played forward automatically using real Kepler propagation.' },
  ],
  equations,
};
